### ISSUE TITLE
HA templete error:

### ISSUE THREAD

**Issue by wifi75** [LeskoIam/kronoterm_cloud_relay#12]
hello  below your template:

![image](https://github.com/user-attachments/assets/f9fdab6c-7fce-479d-b4cc-b0713b08ff75)

template:
```
  - sensor:
  # System info
  - name: "Heat pump id"
    unique_id: heat_pump_id
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'hp_id') }}"
   
  - name: "Heat pump location name"
    unique_id: heat_pump_location_name
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'location_name') }}"
    
  - name: "Heat pump room temperature"
    unique_id: heat_pump_room_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').room_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement

  - name: "Heat pump outlet temperature"
    unique_id: heat_pump_outlet_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').outlet_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement

  - name: "Heat pump outside temperature"
    unique_id: heat_pump_outside_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').outside_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    
  - name: "Sanitary water temperature"
    unique_id: sanitary_water_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').sanitary_water_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
  
  - name: "Heating system pressure"
    unique_id: heat_pump_heating_system_pressure
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').heating_system_pressure }}"
    unit_of_measurement: bar
    device_class: pressure
    state_class: measurement

  - name: "Heat pump working function"
    unique_id: heat_pump_working_function
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').working_function }}"
  
  # Heating loop 1 (radiators)
  - name: "Heat pump loop 1 current temperature"
    unique_id: heating_loop_1_current_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_1').current_temp }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
  
  - name: "Heat pump loop 1 target temperature"
    unique_id: heating_loop_1_target_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_1').target_temp }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
  
  - name: "Heat pump loop 1 calculated target temperature"
    unique_id: heating_loop_1_calculated_target_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_1').calc_target_temp }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement

  - name: "Heat pump loop 1 working status"
    unique_id: heating_loop_1_working_status
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_1').working_status }}"
  
  - name: "Heat pump loop 1 working mode"
    unique_id: heating_loop_1_working_mode
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_1').working_mode }}"
  
  # Heating loop 2 (radiators)
  - name: "Heat pump loop 2 target temperature"
    unique_id: heating_loop_2_target_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_2').target_temp }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
  
  - name: "Heat pump loop 2 calculated target temperature"
    unique_id: heating_loop_2_calculated_target_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_2').calc_target_temp }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement

  - name: "Heat pump loop 2 working status"
    unique_id: heating_loop_2_working_status
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_2').working_status }}"
  
  - name: "Heat pump loop 2 working mode"
    unique_id: heating_loop_2_working_mode
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'heating_loop_2').working_mode }}"
```

**Comment by LeskoIam** [comment]
I think you will have to figure out this one by yourself. 
I have split configuration files in multiple directories, let me explain:

File: `/sensors/heat_pump.yaml`
```yaml
# Main sensor with all the data
- platform: rest
  name: Kronoterm heat pump
  unique_id: kronoterm_heat_pump
  scan_interval: 60
  resource: http://ip-or-host:8555/hp_info/info_summary
  value_template: "{{ value_json.data.system_info.working_function }}"
  json_attributes_path: '$.data'
  json_attributes:
    - hp_id
    - location_name
    - user_level
    - heating_loop_names
    - alarms
    - system_info
    - heating_loop_1
    - heating_loop_2
```
File: `custom_templates.yaml`
```yaml
- sensor:
  # System info
  - name: "Heat pump id"
    unique_id: heat_pump_id
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'hp_id') }}"
   
  - name: "Heat pump location name"
    unique_id: heat_pump_location_name
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'location_name') }}"
    
  - name: "Heat pump room temperature"
    unique_id: heat_pump_room_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').room_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement

  - name: "Heat pump outlet temperature"
    unique_id: heat_pump_outlet_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').outlet_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement

  - name: "Heat pump outside temperature"
    unique_id: heat_pump_outside_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').outside_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    
  - name: "Sanitary water temperature"
    unique_id: sanitary_water_temperature
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').sanitary_water_temperature }}"
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
  
  - name: "Heating system pressure"
    unique_id: heat_pump_heating_system_pressure
    state: "{{ state_attr('sensor.kronoterm_heat_pump', 'system_info').heating_system_pressure }}"
    unit_of_measurement: bar
...
..
.
```
File: `configuration.yaml`
```yaml
template: !include custom_templates.yaml
sensor: !include_dir_merge_list ./sensors

rest_command:
  hp_set_mode_loop_1_on:
    url: http://ip-or-host:8555/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "ON", "heating_loop": 1}'
    content_type: 'application/json'
  hp_set_mode_loop_1_off:
    url: http://ip-or-host:8555/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "OFF", "heating_loop": 1}'
    content_type: 'application/json'
  hp_set_mode_loop_1_auto:
    url: http://ip-or-host:8555/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "AUTO", "heating_loop": 1}'
    content_type: 'application/json'
    
  hp_set_mode_loop_2_on:
    url: http://ip-or-host:8555/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "ON", "heating_loop": 2}'
    content_type: 'application/json'
  hp_set_mode_loop_2_off:
    url: http://ip-or-host:8555/hp_control/se
...
..
.
```

So some tinkering will be necessary I think this will get you started.

**Comment by wifi75** [comment]
my configuration now it is as below:

```

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
light: !include light.yaml
media_player: !include media_player.yaml
cover: !include cover.yaml 
climate: !include climate.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml



homeassistant:

  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_named packages
```

how i can add this ?

template: !include custom_templates.yaml
sensor: !include_dir_merge_list ./sensors

**Comment by wifi75** [comment]
could i copy all my yaml files into the package directory, just like i do with my other yaml files?

**Comment by LeskoIam** [comment]
You could paste from "my" `/sensors/heat_pump.yaml` to your `sensors.yaml` and add the 
```yaml
template: !include custom_templates.yaml`
```
under your other includes.

Make sure you don't have duplicate `!includes`!

I don't know you have set up your system so I can't tell you a lot more.

**Comment by wifi75** [comment]
can you post your  HA dashboard for kronoterm pump please?

**Comment by LeskoIam** [comment]
![hp_dash_01](https://github.com/user-attachments/assets/fb70abb4-c731-4278-b54f-ba073131f94d)
![hp_dash_02](https://github.com/user-attachments/assets/efda712c-c252-4854-92fa-c5680740330a)
![hp_dash_03](https://github.com/user-attachments/assets/bc8850b7-8d3f-4164-ae76-d32bc1e02bcf)
![hp_dash_04](https://github.com/user-attachments/assets/4bc21260-c825-45a3-a0f6-489a4543c7e5)

**Comment by wifi75** [comment]
oh yes thank you!!!


but this  what is it for? you also have nothing that recalls this code..


```

rest_command:
  hp_set_mode_loop_1_on:
    url: http://192.168.1.131:8555/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "ON", "heating_loop": 1}'
    content_type: 'application/json'
  hp_set_mode_loop_1_off:
    url: http://192.168.1.131/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "OFF", "heating_loop": 1}'
    content_type: 'application/json'
  hp_set_mode_loop_1_auto:
    url: http://192.168.1.131/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "AUTO", "heating_loop": 1}'
    content_type: 'application/json'
    
  hp_set_mode_loop_2_on:
    url: http://192.168.1.131:8555/hp_control/set_heating_loop_mode
    method: POST
    payload: '{"mode": "ON", "heating_loop": 2}'
    content_type: 'application/json'
  hp_set_mode_loop_2_off:
    url: http://192.168.1.131:8555/hp_control/se
```
