### ISSUE TITLE
`code 400, message Bad request version`

### ISSUE THREAD

**Issue by LeskoIam** [LeskoIam/kronoterm_cloud_relay#25]
When running in docker on debian I get the following message:

```
192.168.0.201 - - [20/Nov/2024 14:30:27] "GET /version HTTP/1.1" 200 -
192.168.0.201 - - [20/Nov/2024 14:30:27] code 400, message Bad request version ('²îë\x822Ñ\x8c^iú_\x03¢å<%pw8çà"\x98¯òY\xad<Çd¹=\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.0.201 - - [20/Nov/2024 14:30:27] "\x16\x03\x01\x07K\x01\x00\x07G\x03\x03X<ý\x97°\x9f»Ò\x0b\x91e¤\x9fCWéK\x07Á¯ùBv\x17CgT\x8f\x8b\x9dU\x84 ²îë\x822Ñ\x8c^iú_\x03¢å<%pw8çà"\x98¯òY­<Çd¹=\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À" 400 -
192.168.0.201 - - [20/Nov/2024 14:30:27] code 400, message Bad request version ('>\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.0.201 - - [20/Nov/2024 14:30:27] "\x16\x03\x01\x02z\x01\x00\x02v\x03\x03X\x05/«èk4}Ù§x^\x8cwû×0\\ï\x8d\x7f!\x17×Aèá\x1e\x91o\x8d3 ²·æ\x91yä\x18\x95n\x15\x8dëwîéÀðL;ÈGh\x7fV\x97\x7f`~\x0f~\x0b>\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À" 400 -
192.168.0.201 - - [20/Nov/2024 14:30:41] "GET /version HTTP/1.1" 200 -
192.168.0.201 - - [20/Nov/2024 14:30:41] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x07A\x01\x00\x07=\x03\x03')
192.168.0.201 - - [20/Nov/2024 14:30:41] "\x16\x03\x01\x07A\x01\x00\x07=\x03\x03\x1fø"\x15®" 400 -
192.168.0.201 - - [20/Nov/2024 14:30:41] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02p\x01\x00\x02l\x03\x03')
192.168.0.201 - - [20/Nov/2024 14:30:41] "\x16\x03\x01\x02p\x01\x00\x02l\x03\x03\x0d\x9fÀ\x9f~ØC" 400 -
192.168.0.201 - - [20/Nov/2024 14:30:58] "GET /version HTTP/1.1" 200 -
192.168.0.201 - - [20/Nov/2024 14:30:59] code 400, message Bad request version ('ÊÂ¹yAÞ\x01ã\x87\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.0.201 - - [20/Nov/2024 14:30:59] "\x16\x03\x01\x07A\x01\x00\x07=\x03\x03ÛQ\x85<Ô\x97\x1b ë8\x08«¥@ä\x81¢ÐÐ}ý·\x1e¬ø÷ÀÈ\x9d#â¤ 5\x86\x0bG\x1b²ÍmX\x90\x98Cè(\x0c\x8d/ÿÏLI\x00\x1eÊÂ¹yAÞ\x01ã\x87\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À" 400 -
192.168.0.201 - - [20/Nov/2024 14:30:59] code 400, message Bad request version ('v\x84®I+\x19Ó:Í\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À')
192.168.0.201 - - [20/Nov/2024 14:30:59] "\x16\x03\x01\x02p\x01\x00\x02l\x03\x03u¬Ø\x1d\x86¾\x82hn\x92\x0e(\x9eÝc\x94"ö·^\x9faªY\x0e*\x9bâîºg\x93 Ï{Spö´6\x9e\x0c\x9e¬ÔrO²Fh^\x15s\x12s\x1dv\x84®I+\x19Ó:Í\x00"\x13\x01\x13\x03\x13\x02À+À/Ì©Ì¨À,À0À" 400 -
```

It also does not work in docker on windows. It only works as standalone.
`Dockerfile`
```yaml
# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./src /app/src

COPY ./pyproject.toml /app
COPY ./requirements.txt /app
COPY ./dev_requirements.txt /app
COPY ./prod_requirements.txt /app
COPY ./LICENSE /app
COPY ./README.md /app


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8555 available to the world outside this container
EXPOSE 8555

# Define environment variable
ENV FLASK_APP=src/kronoterm_cloud_relay.py

# Run app.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=8555"]
```
`docker-compose.yml`
```yaml
services:
  kronoterm_cloud_relay:
    image: leskoiam/kronoterm_cloud_relay:latest
    container_name: kronoterm_cloud_relay
    restart: unless-stopped
    ports:
      - "8555:8555"  # Adjust the port mappings as needed
    environment:
      # Add your kronoterm cloud username and password
      - KRONOTERM_CLOUD_USER=****
      - KRONOTERM_CLOUD_PASSWORD=****
```
