### ISSUE TITLE
Running in docker container is very slow

### ISSUE THREAD

**Issue by LeskoIam** [LeskoIam/kronoterm_cloud_relay#26]
Not just on debian, also on windows10 machine. Using the following docker configuration:

`Dockerfile`
```yaml
# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./src /app/src

COPY ./pyproject.toml /app
COPY ./requirements.txt /app
COPY ./dev_requirements.txt /app
COPY ./prod_requirements.txt /app
COPY ./LICENSE /app
COPY ./README.md /app


# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
# Make port 8555 available to the world outside this container
EXPOSE 8555


# Run app when the container launches
CMD ["fastapi", "run", "src/kronoterm_cloud_relay.py", "--host=0.0.0.0", "--port=8555"]
```
`docker-compose.yml`
```yaml
services:
  kronoterm_cloud_relay:
    image: leskoiam/kronoterm_cloud_relay:latest
    container_name: kronoterm_cloud_relay
    restart: unless-stopped
    ports:
      - "8555:8555"  # Adjust the port mappings as needed
    environment:
      # Add your kronoterm cloud username and password
      - KRONOTERM_CLOUD_USER="your-user"
      - KRONOTERM_CLOUD_PASSWORD="your-password"


```
